---
- name: Ensure dotfiles repository is cloned locally
  ansible.builtin.git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_repo_local_destination }}"
    version: "{{ dotfiles_repo_version }}"
    force: "{{ dotfiles_repo_force }}"
    accept_hostkey: "{{ dotfiles_repo_accept_hostkey }}"
  become: false

- name: Ensure all configured dotfiles are links
  ansible.builtin.command: "ls -F {{ dotfiles_home }}/{{ item }}"
  register: existing_dotfile_info
  failed_when: false
  check_mode: false
  changed_when: false
  with_items: "{{ dotfiles_files }}"

- name: Remove existing dotfiles file if a replacement is being linked
  ansible.builtin.file:
    path: "{{ dotfiles_home }}/{{ dotfiles_files[item.0] }}"
    state: absent
  loop_control:
    label: "{{ dotfiles_files[item.0] }}"
  when: "'@' not in item.1.stdout"
  with_indexed_items: "{{ existing_dotfile_info.results }}"

- name: Get list of directories
  ansible.builtin.shell: set -o pipefail && find . -maxdepth 5 -type d | grep -E 'scripts|.config|.mozilla|.ansible' | cut -c 3-
  args:
    executable: "{{ '/bin/bash' if ansible_system == 'Linux' else '/bin/sh' }}"
    chdir: "{{ dotfiles_repo_local_destination }}"
  register: dotfiles_dirs
  changed_when: false

- name: Prepare directories
  ansible.builtin.file:
    dest: "{{ dotfiles_home }}/{{ item }}"
    state: directory
    mode: 0755
  become: false
  with_items: "{{ dotfiles_dirs.stdout_lines }}"

- name: Link dotfiles
  ansible.builtin.file:
    src: "{{ dotfiles_repo_local_destination }}/{{ item }}"
    dest: "{{ dotfiles_home }}/{{ item }}"
    state: link
    mode: 0644
    follow: false
  become: false
  with_items: "{{ dotfiles_files|reject('match', '([a-zA-Z0-9-/\\s_\\.\\-\\(\\):])+\\.(sh|py)')|list }}"

- name: Link scripts
  ansible.builtin.file:
    src: "{{ dotfiles_repo_local_destination }}/{{ item }}"
    dest: "{{ dotfiles_home }}/{{ item }}"
    state: link
    mode: 0755
    follow: false
  become: false
  with_items: "{{ dotfiles_files|select('match', '([a-zA-Z0-9-/\\s_\\.\\-\\(\\):])+\\.(sh|py)')|list }}"
