---

- name: Converge
  hosts: all
  vars:
    # since ansible still expecting py2
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Include git role
      ansible.builtin.include_role:
        name: "charlesrocket.git"
        apply:
          become: true

    - name: Include dotfiles role
      ansible.builtin.include_role:
        name: "charlesrocket.dotfiles"
